model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/loss"
    save_top_k: 1
    save_last: True
    mode: "max"
    verbose: False
    dirpath: 'checkpoints/'
    filename: '{epoch:02d}'

early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/loss"
    patience: 100
    mode: "max"
    min_delta: 0