model_checkpoint:
    #_target_: pytorch_lightning.callbacks.ModelCheckpoint
    _target_: ml.utils.mlflow_utils.MLFlowModelCheckpoint
    monitor: "val/loss"
    save_top_k: 5
    save_last: True
    mode: "min"
    verbose: False
    dirpath: 'checkpoints/'
    filename: '{epoch:02d}'

early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/loss"
    patience: 100
    mode: "min"
    min_delta: 0