# @package _global_

# default configuration
defaults:
    # model config
    - trainer: default_trainer.yaml
    - datamodule: custom_datamodule.yaml
    - callbacks: default_callbacks.yaml
    - logger: mlflow.yaml
    # enable color logging
    # - override hydra/hydra_logging: colorlog
    # - override hydra/job_logging: colorlog

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
run_name: ${now:%Y-%m-%d_%H-%M-%S}
log_dir: logs/runs/${logger.mlflow.experiment_name}/${run_name}

# use `python main.py debug=true` for easy debugging
# this will run 1 train, val and test loop with only 1 batch
debug: False
disable_warnings: True

hydra:
    # output paths for hydra logs
    run:
        dir: ${log_dir}
    sweep:
        dir: logs/multiruns/${run_name}
        subdir: ${hydra.job.num}
