# @package _global_

# default configuration for evaluation
defaults:
    # add further config for evaluation
    - trainer: default_trainer.yaml
    - datamodule: mnist_datamodule.yaml
    - callbacks: default_callbacks.yaml
    - logger: mlflow.yaml


logger:
    mlflow:
      tags:
        stage: eval


work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
run_name: ${now:%Y-%m-%d_%H-%M-%S}
log_dir: logs/runs/${logger.mlflow.experiment_name}/${run_name}


disable_warnings: True

hydra:
    # output paths for hydra logs
    run:
        dir: ${log_dir}
    sweep:
        dir: logs/multiruns/${run_name}
        subdir: ${hydra.job.num}

    output_subdir: null
